use_frameworks!

platform :ios, '8.0'

target 'AvoStateOfTracking_Example' do
  pod 'AvoStateOfTracking', :path => '../'

  target 'AvoStateOfTracking_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
    pod 'OCMock'
  end
end
