use_frameworks!

platform :ios, '10.0'

target 'AvoStateOfTracking_Example' do
  pod 'AvoStateOfTracking', :path => '../'
  pod 'Analytics', '~> 3.6.0'

  target 'AvoStateOfTracking_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
    pod 'OCMock'
  end
end
