use_frameworks!

platform :ios, '12.0'

target 'AvoStateOfTracking_Example' do
  pod 'AvoInspector', :path => '../'
  pod 'Analytics', '~> 3.6.0'

  target 'AvoStateOfTracking_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
    pod 'OCMock'
  end
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end
