name: iOS Objective-C

on:
  pull_request:
    types: [opened, reopened, unlocked, synchronize]

jobs:
  Tests:
    runs-on: macos-latest

    env:
      project-path: ./Example
      simulator: iOS Simulator,OS=latest,name=iPhone 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Cocoapods cache
        uses: actions/cache@v4
        id: cocoapods-cache
        with:
          path: ${{ env.project-path }}/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles(format('{0}/{1}', env.project-path, 'Podfile.lock')) }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install iOS project dependencies
        if: steps.cocoapods-cache.outputs.cache-hit != 'true'
        run: pod install
        working-directory: ${{ env.project-path }}

      - name: Test
        run: |
          set -o pipefail
          xcodebuild -workspace AvoStateOfTracking.xcworkspace -scheme AvoStateOfTracking-Example -destination platform='${{ env.simulator }}' clean test | xcpretty
        working-directory: ${{ env.project-path }}
